const express = require('express');
const router = express.Router();
const supabase = require('../lib/supabase');
const { requireAuth } = require('../middleware/auth');
const { requireRole } = require('../middleware/roles');

// GET /api/projects/:projectId/cards
// List tickets for a project
router.get('/:projectId/cards', requireAuth, async (req, res) => {
  try {
    const { projectId } = req.params;
    let query = supabase
      .from('cards')
      .select(`
        *,
        assignee:profiles!cards_assignee_id_fkey(full_name, avatar_url),
        reporter:profiles!cards_reporter_id_fkey(full_name, avatar_url)
      `)
      .eq('project_id', projectId)
      .order('created_at', { ascending: false });

    // Optional filters
    if (req.query.status) query = query.eq('status', req.query.status);
    if (req.query.priority) query = query.eq('priority', req.query.priority);
    if (req.query.assignee_id) query = query.eq('assignee_id', req.query.assignee_id);

    const { data: cards, error } = await query;
    if (error) throw error;
    res.json(cards);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to fetch cards' });
  }
});

// GET /api/projects/:projectId/cards/:id
// Get single card
router.get('/:projectId/cards/:id', requireAuth, async (req, res) => {
  try {
    const { data: card, error } = await supabase
      .from('cards')
      .select(`
        *,
        assignee:profiles!cards_assignee_id_fkey(full_name, avatar_url),
        reporter:profiles!cards_reporter_id_fkey(full_name, avatar_url)
      `)
      .eq('id', req.params.id)
      .eq('project_id', req.params.projectId)
      .single();

    if (error) {
      if (error.code === 'PGRST116') return res.status(404).json({ error: 'Card not found' });
      throw error;
    }
    res.json(card);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to fetch card' });
  }
});

// POST /api/projects/:projectId/cards
// Create a card (NIYO-1 ID is auto-generated by DB trigger)
router.post('/:projectId/cards', requireAuth, requireRole('admin', 'pm', 'member'), async (req, res) => {
  try {
    const { projectId } = req.params;
    const { title, description, issue_type, priority, assignee_id, story_points, list_id, sprint_id, rank } = req.body;

    if (!title) {
      return res.status(400).json({ error: 'Title is required' });
    }

    const { data: card, error } = await supabase
      .from('cards')
      .insert({
        project_id: projectId,
        title,
        description,
        issue_type: issue_type || 'task',
        priority: priority || 'medium',
        status: 'backlog', // Start in backlog by default
        assignee_id,
        reporter_id: req.user.id,
        story_points,
        list_id: list_id || null,
        sprint_id: sprint_id || null,
        rank: rank || 0
      })
      .select()
      .single();

    if (error) throw error;

    // Log the creation
    await supabase.from('activity_log').insert({
      card_id: card.id,
      user_id: req.user.id,
      action: 'created',
      details: { title }
    });

    res.status(201).json(card);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to create card' });
  }
});

// PUT /api/projects/:projectId/cards/:id
// Update a card
router.put('/:projectId/cards/:id', requireAuth, requireRole('admin', 'pm', 'member'), async (req, res) => {
  try {
    const { title, description, issue_type, priority, status, assignee_id, story_points, list_id, sprint_id, rank, start_date, due_date, is_archived } = req.body;

    const { data: card, error } = await supabase
      .from('cards')
      .update({
        title,
        description,
        issue_type,
        priority,
        status,
        assignee_id,
        story_points,
        list_id: list_id !== undefined ? list_id : undefined,
        sprint_id: sprint_id !== undefined ? sprint_id : undefined,
        rank: rank !== undefined ? rank : undefined,
        start_date: start_date !== undefined ? start_date : undefined,
        due_date: due_date !== undefined ? due_date : undefined,
        is_archived: is_archived !== undefined ? is_archived : undefined,
        updated_at: new Date()
      })
      .eq('id', req.params.id)
      .eq('project_id', req.params.projectId)
      .select()
      .single();

    if (error) throw error;

    // Log the update
    await supabase.from('activity_log').insert({
      card_id: card.id,
      user_id: req.user.id,
      action: 'updated',
      details: { fields: req.body }
    });

    res.json(card);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to update card' });
  }
});

// DELETE /api/projects/:projectId/cards/:id
router.delete('/:projectId/cards/:id', requireAuth, requireRole('admin', 'pm'), async (req, res) => {
  try {
    const { error } = await supabase
      .from('cards')
      .delete()
      .eq('id', req.params.id)
      .eq('project_id', req.params.projectId);

    if (error) throw error;
    res.status(204).send();
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to delete card' });
  }
});

module.exports = router;
